spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hcl
    username: postgres
    password: True2you
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # dev only; prefer Flyway/Liquibase in prod
    properties:
      hibernate:
        format_sql: true
        default_schema: customer
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

server:
  port: 8990
